apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample

commonLabels:
  namespace: sample
  env: prod-environment

bases:
- ../../../../manifests/sample/sample-api

resources:
- service-mapping.yaml

patchesStrategicMerge:
- hpa.yaml
- deployment.yaml

configMapGenerator:
- name: sample-api
  namespace: sample
  files: [application-overrides.yaml]
  env: config.env

secretGenerator:
- name: sample-api
  namespace: sample
  env: secrets.env
  type: Opaque

images:
-
  name: docker.io/sample/sample-api
  newTag: "latest"
