apiVersion: v1
kind: Service
metadata:
  name: sample-worker
  namespace: sample
  labels:
    app: sample-worker
spec:
  selector:
    app: sample-worker
  ports:
    - name: sample-worker
      targetPort: 8080
      port: 8080
