apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka
commonLabels:
  namespace: kafka
  env: local

bases:
- git@github.com:skafld/skafld-infrastructure.git//infra/kubernetes/manifests/kafka/kafka
