apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample

commonLabels:
  namespace: sample
  env: qa-environment

bases:
- ../../../../manifests/sample/sample-worker


patchesStrategicMerge:
- hpa.yaml
- deployment.yaml

configMapGenerator:
- name: sample-worker
  namespace: sample
  files: [application-overrides.yaml]
  env: config.env

secretGenerator:
- name: sample-worker
  namespace: sample
  env: secrets.env
  type: Opaque

images:
-
  name: docker.io/sample/sample-worker
  newTag: "latest"
