---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
  namespace: sample
  labels:
    app: sample-api
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      volumes:
        - name: sample-api
          configMap:
            name: sample-api
      containers:
      - name: sample-api
        image: docker.io/sample/sample-api:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          -
            name: sample-api
            mountPath: /usr/share/skafld/application-overrides.yaml
            subPath: application-overrides.yaml
        envFrom:
          -
            secretRef:
              name: sample-api
          -
            configMapRef:
              name: sample-api
        env:
          -
            name: SPRING_PROFILES_ACTIVE
            value: "default,overrides"
          -
            name: SPRING_CONFIG_ADDITIONAL-LOCATION
            value: /usr/share/skafld/application-overrides.yaml
          -
            name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - name: java
          containerPort: 8080
        - name: management
          containerPort: 8001
        readinessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: "/actuator/health/readiness"
            port: 8001
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: "/actuator/health/liveness"
            port: 8001
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 500m
            memory: 768Mi
