region: ENC[AES256_GCM,data:ZLi1rgmtoZFQ,iv:asDtcFIXgmFVZOwpilYyBZSFCgo8FZb/PSkygSmJDXo=,tag:t7ejYcICnBKtdLUfZt81VQ==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:081685684219:key/db52c10c-f288-47fc-9a50-d2902eab2ffc
        created_at: '2020-08-12T22:52:23Z'
        enc: AQICAHi4NypVobG83X8BbK7J0vb4ln7N+AdKtpntiHiUkp97ZwHdfTzEu+x1HdNe5k344H/RAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMW1IZ7O99m2vspGMPAgEQgDsS3chY75znWTeN975LLHdI/exxlcX/2yQRQ4GraxXDS++NXcvJ5ggWkju5HM14JSbEPFR8vp/aWqYrSg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-08-12T22:52:43Z'
    mac: ENC[AES256_GCM,data:yHezh6o6yiJWCyUREZWeH2R2vwNFFa2HQm93LulLWHa2bmefSh3JYYnqpaNtOH6AGN4WJSfWxqIc5kKqwt/lT4BqPYXMUjT4svA448ghRAwOgxaaSyqcQu7t+a01+b7HrW9Sta0QAMqAEgfFoQaX1Orke7Pg35aQ3FoM8Pmky2o=,iv:KiQWkXpRnrJFym9CjJ00kgfts3fcehkw77RQMDbQoP4=,tag:1b6NWgUPJeVSZT8dbD7/CA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
