name: Build Static
on:
  repository_dispatch:
    types: [ build-spa ]
  workflow_dispatch:
    inputs:
      env:
        description: 'qa-environment | prod-environment | dev-environment'
        default: 'qa-environment'
        required: true
      ref:
        description: Git Ref (Default to workflow branch)
        required: false

jobs:
  frontend:
    name: "Build Static"
    uses: skafld/github-actions/.github/workflows/frontend-build-spa.yaml@main
    with:
      env: ${{ github.event.inputs.env }}
      node_version: '14'
      frontend_modules: '["sample-ui"]'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI_PAT: ${{ secrets.CI_PAT }}
      ID_RSA: ${{ secrets.ID_RSA }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ASSUMABLE_ROLES_MAP: ${{ secrets.AWS_ASSUMABLE_ROLES_MAP }}
