name: Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  generator:
    name: "Generator"
    uses: skafld/github-actions/.github/workflows/generator.yaml@v2
    with:
      generator: "skafld:java"
      untracked_files: |
        [
          ".github/workflows/generator.yaml",
          "infra/kubernetes/config/*",
          "infra/terraform/config/*",
          "infra/terraform/main.tf",
          "infra/terraform/modules/*",
          "infra/terraform/outputs.tf",
          "infra/terraform/versions.tf",
          "pom.xml",
          "sample-api/pom.xml",
          "sample-api/src/*",
          "sample-worker/pom.xml",
          "sample-worker/src/*"
        ]
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
