name: Pre Release
on:
  release:
    types: [prereleased]

jobs:
  prerelease:
    name: "Pre Released"
    uses: skafld/github-actions/.github/workflows/prerelease.yaml@main
    secrets:
      CI_PAT: ${{ secrets.CI_PAT }}
