name: Release
on:
  release:
    types: [released]

jobs:

  release:
    name: "Release"
    uses: skafld/github-actions/.github/workflows/release.yaml@v2
    with:
      env: prod-environment
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

